import{a as L,S as b,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=e(t);fetch(t.href,n)}})();const w="52399913-eb814ceb32c08bc3c85c670ba";async function u(o,s,e){try{return(await L.get("https://pixabay.com/api/",{params:{key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:e}})).data}catch(r){throw r}}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),p=document.querySelector(".load-more"),v=new b(".gallery a",{captionsData:"alt",captionDelay:250});function m(o){const s=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",s),v.refresh()}function S(){f.innerHTML=""}function y(){h.classList.remove("is-hidden")}function g(){h.classList.add("is-hidden")}function q(){p.classList.remove("is-hidden")}function M(){p.classList.add("is-hidden")}const $=document.querySelector(".form"),B=document.querySelector(".gallery"),P=document.querySelector(".load-more");let i=1,c=15,d="";$.addEventListener("submit",x);P.addEventListener("click",E);async function x(o){o.preventDefault();const e=o.currentTarget.elements["search-text"].value.trim();if(e){d=e,i=1,S(),M(),y();try{const r=await u(d,i,c);if(r.hits.length===0){a.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(r.hits),r.totalHits>c&&q()}catch(r){console.error("Помилка при отриманні зображення:",r),a.info({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{g()}}}async function E(){i+=1,y();try{const o=await u(d,i,c);m(o.hits);const{height:s}=B.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),i*c>=o.totalHits&&(hideLoadMoreButton(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(o){console.log("Помилка при завантаженні наступної сторінки:",o),a.error({title:"Error",message:"Could not load more images.",position:"topRight"})}finally{g()}}
//# sourceMappingURL=index.js.map
