import{a as w,S as v,i as n}from"./assets/vendor-BSTwZ_tR.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S="52399913-eb814ceb32c08bc3c85c670ba",P="https://pixabay.com/api/",R=15;async function f(o,s){try{const{data:e}=await w.get(P,{params:{key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:R}});return e}catch(e){throw e}}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".load-more"),q=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const s=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
        </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",s),q.refresh()}function E(){p.innerHTML=""}function b(){m.classList.remove("is-hidden")}function L(){m.classList.add("is-hidden")}function u(){y.classList.remove("is-hidden")}function c(){y.classList.add("is-hidden")}const x=document.querySelector(".form"),$=document.querySelector(".gallery"),I=document.querySelector(".load-more");let a=1;const l=15;let h="";x.addEventListener("submit",M);I.addEventListener("click",B);async function M(o){o.preventDefault();const e=o.currentTarget.elements["search-text"].value.trim();if(!e){n.error({title:"Error",message:"Введіть пошуковий запит.",position:"topRight"});return}h=e,a=1,E(),c(),b();try{const i=await f(h,a);if(i.hits.length===0){n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(i.hits),i.totalHits>a*l&&i.hits.length===l?u():(c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c(),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}}async function B(){a+=1,c(),b();try{const o=await f(h,a);g(o.hits);const{height:s}=$.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),a*l>=o.totalHits||o.hits.length<l?(c(),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):u()}catch{u(),n.error({title:"Error",message:"Could not load more images.",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
